version: '3.9'

services:
  crudapp:
    container_name: crud
    build: .
    ports:
      - "8000:8000"
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=admin
      - PG_DB=postgres
      - PG_PORT=5432
      - PG_HOST=db
    depends_on:
      - db

  db:
   container_name: db
   image: postgres:latest
   environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
   ports:
      - "5432:5432"
   volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}